name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Deploy MkDocs Documentation
        run: |
          echo "Starting MkDocs deployment..."
          mkdocs gh-deploy -f RLM_Booking/RLM-docs/mkdocs.yml --force
          echo "MkDocs deployment completed successfully."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
