name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material  # Note to Self: Add more MkDocs plugins here

      - name: Build and Deploy Documentation
        run: |
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
